CREATE TABLE admin (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE universities (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    abbreviation VARCHAR(50) NOT NULL,
    photo VARCHAR
);

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    mail VARCHAR(255) UNIQUE NOT NULL,
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    profile_photo VARCHAR(255),
    university_id INT REFERENCES universities(id) ON DELETE CASCADE
);

CREATE TABLE follower_table (
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    follows INT REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, follows)
);

CREATE TABLE animals (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    kind VARCHAR(255) NOT NULL,
    added_by INT REFERENCES users(id) ON DELETE CASCADE,
    profile_photo VARCHAR(255),
    university_id INT REFERENCES universities(id) ON DELETE CASCADE,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    image VARCHAR(255),
    description TEXT,
    posted_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE post_animals (
    post_id INT REFERENCES posts(id) ON DELETE CASCADE,
    animal_id INT REFERENCES animals(id) ON DELETE CASCADE
);


CREATE TABLE comments_post (
    id SERIAL PRIMARY KEY,
    post_id INT REFERENCES posts(id) ON DELETE CASCADE,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    comment TEXT NOT NULL,
    added_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    like_count INT DEFAULT 0,
    dislike_count INT DEFAULT 0
);

CREATE TABLE comments_animal (
    id SERIAL PRIMARY KEY,
    animal_id INT REFERENCES animals(id) ON DELETE CASCADE,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    comment TEXT NOT NULL,
    added_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    like_count INT DEFAULT 0,
    dislike_count INT DEFAULT 0
);

CREATE TABLE  IF NOT EXISTS rooms (
    id SERIAL PRIMARY KEY,
    constructor_id INT REFERENCES users(id) ON DELETE SET NULL,
    is_public BOOLEAN,
    room_photo VARCHAR(255),
    room_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS  participants (
    room_id INT REFERENCES rooms(id) ON DELETE CASCADE,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (room_id, user_id)
);

CREATE TABLE IF NOT EXISTS  messages (
    room_id INT REFERENCES  rooms(id) ON DELETE CASCADE,
    user_id INT REFERENCES  users(id) ON DELETE SET NULL,
    message TEXT,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS animal_likes (
    animal_id INT REFERENCES animals(id) ON DELETE CASCADE,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    is_like BOOLEAN,
    PRIMARY KEY (animal_id, user_id)
);

CREATE TABLE IF NOT EXISTS post_likes (
    post_id INT REFERENCES posts(id) ON DELETE CASCADE,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    is_like BOOLEAN,
    PRIMARY KEY (post_id, user_id)
);

INSERT INTO universities (name, abbreviation, photo)
VALUES ('Abdullah Gül Üniversitesi', 'agu', 'https://toptalent.co/Uploads/CKImages/abdullah%20g%C3%BCl%20%C3%BCniversitesi%20logo.jpg'),
('Adana Alparslan Türkeş Bilim ve Teknoloji  Üniversitesi', 'atu', 'https://toptalent.co/Uploads/CKImages/adana.png'),
('Adıyaman Üniversitesi', 'adiyaman', 'https://toptalent.co/Uploads/CKImages/Adiyaman%20%C3%BCniversitesi.jpg'),
('Afyon Kocatepe Üniversitesi', 'aku', 'https://toptalent.co/Uploads/CKImages/afyom%20kocatepe.jpg'),
('Afyonkarahisar Sağlık Bilimleri Üniversitesi', 'afsu', 'https://toptalent.co/Uploads/CKImages/afyonkarahisar%20sa%C4%9Fl%C4%B1k%20bilimleri.png'),
('Ağrı İbrahim Çeçen Üniversitesi', 'agri', 'https://toptalent.co/Uploads/CKImages/d3aef49e10d5243e770fb69766a4b22f(2).png'),
('Akdeniz Üniversitesi', 'akdeniz', 'https://toptalent.co/Uploads/CKImages/Akdeniz%20Universitesi-tr.png'),
('Aksaray Üniversitesi', 'aksaray', 'https://toptalent.co/Uploads/CKImages/aksaray%20%C3%BCniversitesi.png'),
('Alanya Alaaddin Keykubat Üniversitesi', 'alanya', 'https://toptalent.co/Uploads/CKImages/Alkulogo.png'),
('Amasya Üniversitesi', 'amasya', 'https://toptalent.co/Uploads/CKImages/amasya_universitesi_logo.png'),
('Anadolu Üniversitesi', 'anadolu', 'https://toptalent.co/Uploads/CKImages/Anadolu_%C3%9Cniversitesi_Logosu.svg.png'),
('Ankara Hacı Bayram Veli Üniversitesi', 'ahbv', 'https://toptalent.co/Uploads/CKImages/ankara%20hac%C4%B1%20bayram%20veli.jpg'),
('Ankara Müzik ve Güzel Sanatlar Üniversitesi', 'mgu', 'https://toptalent.co/Uploads/CKImages/ankara%20m%C3%BCzik%20ve%20g%C3%BCzel%20sanatlar.jpg'),
('Ankara Sosyal Bilimler Üniversitesi', 'asbu', 'https://toptalent.co/Uploads/CKImages/ankara%20sosyal%20bilimler.jpg'),
('Ankara Üniversitesi', 'ankara', 'https://toptalent.co/Uploads/CKImages/ankara%20%C3%BCniversitesi.jpg'),
('Ankara Yıldırım Beyazıt Üniversitesi', 'aybu', 'https://toptalent.co/Uploads/CKImages/ankara%20y%C4%B1ld%C4%B1r%C4%B1m%20beyaz%C4%B1t.png'),
('Ardahan Üniversitesi', 'ardahan', 'https://toptalent.co/Uploads/CKImages/ardahan%20%C3%BCniversitesi.jpg'),
('Artvin Çoruh Üniversitesi', 'artvin', 'https://toptalent.co/Uploads/CKImages/artvin%20%C3%A7oruh.png'),
('Atatürk Üniversitesi', 'atauni', 'https://toptalent.co/Uploads/CKImages/Ataturkuni_logo.png'),
('Aydın Adnan Menderes Üniversitesi', 'adu', 'https://toptalent.co/Uploads/CKImages/ayd%C4%B1n%20adnan%20menderes.jpg'),
('Balıkesir Üniversitesi', 'balikesir', 'https://toptalent.co/Uploads/CKImages/Balikesiruni.jpg'),
('Bandırma Onyedi Eylül Üniversitesi', 'bandirma', 'https://toptalent.co/Uploads/CKImages/band%C4%B1rma%20onyedi%20eyl%C3%BCl.png'),
('Bartın Üniversitesi', 'bartin', 'https://toptalent.co/Uploads/CKImages/Bart%C4%B1n_%C3%9Cniversitesi_logosu.jpg'),
('Batman Üniversitesi', 'batman', 'https://toptalent.co/Uploads/CKImages/Batman_%C3%9Cniversitesi_logosu.jpg'),
('Bayburt Üniversitesi', 'bayburt', 'https://toptalent.co/Uploads/CKImages/bayburt%20%C3%BCniversitesi.jpg'),
('Bilecik Şeyh Edebali Üniversitesi', 'bilecik', 'https://toptalent.co/Uploads/CKImages/bilecik%20%C5%9Feyh%20edebali.jpg'),
('Bingöl Üniversitesi', 'bingol', 'https://toptalent.co/Uploads/CKImages/bing%C3%B6l%20%C3%BCniversitesi.jpg'),
('Bitlis Eren Üniversitesi', 'bitliseren', 'https://toptalent.co/Uploads/CKImages/Bitlis_Eren_%C3%9Cniversitesi_logosu.jpg'),
('Boğaziçi Üniversitesi', 'boun', 'https://toptalent.co/Uploads/CKImages/bo%C4%9Fazi%C3%A7i%20%C3%BCniversitesi.png'),
('Bolu Abant İzzet Baysal Üniversitesi', 'ibu', 'https://toptalent.co/Uploads/CKImages/aibu_logo(1).jpg'),
('Burdur Mehmet Akif Ersoy Üniversitesi', 'mehmetakif', 'https://toptalent.co/Uploads/CKImages/burdur%20mehmet%20akif%20ersoy.jpg'),
('Bursa Teknik Üniversitesi', 'btu', 'https://toptalent.co/Uploads/CKImages/bursa%20teknik.jpg'),
('Bursa Uludağ Üniversitesi', 'uludag', 'https://toptalent.co/Uploads/CKImages/bursa%20uluda%C4%9F.jpg'),
('Çanakkale Onsekiz Mart Üniversitesi', 'comu', 'https://toptalent.co/Uploads/CKImages/%C3%A7anakkale%2018%20mart%20%C3%BCniversitesi.png'),
('Çankırı Karatekin Üniversitesi', 'karatekin', 'https://toptalent.co/Uploads/CKImages/%C3%A7ank%C4%B1r%C4%B1%20karatekin.png'),
('Çukurova Üniversitesi', 'cu', 'https://toptalent.co/Uploads/CKImages/%C3%A7ukurova.png'),
('Dicle Üniversitesi', 'dicle', 'https://toptalent.co/Uploads/CKImages/dicle%20%C3%BCniversitesi.png'),
('Dokuz Eylül Üniversitesi', 'deu', 'https://toptalent.co/Uploads/CKImages/dokuz%20eyl%C3%BCl.jpg'),
('Düzce Üniversitesi', 'duzce', 'https://toptalent.co/Uploads/CKImages/d%C3%BCzce%20%C3%BCniversitesi.png'),
('Ege Üniversitesi', 'ege', 'https://toptalent.co/Uploads/CKImages/ege%20%C3%BCni.jpg'),
('Erciyes Üniversitesi', 'erciyes', 'https://toptalent.co/Uploads/CKImages/erciyes%20%C3%BCniversitesi.jpg'),
('Erzincan Binali Yıldırım Üniversitesi', 'ebyu', 'https://toptalent.co/Uploads/CKImages/erzincan%20Binali%20Y%C4%B1ld%C4%B1r%C4%B1m%20%C3%BCniversitesi.jpg'),
('Erzurum Teknik Üniversitesi', 'erzurum', 'https://toptalent.co/Uploads/CKImages/erzurum%20teknik.png'),
('Eskişehir Osmangazi Üniversitesi', 'ogu', 'https://toptalent.co/Uploads/CKImages/eski%C5%9Fehir%20osmangazi.png'),
('Eskişehir Teknik Üniversitesi', 'eskisehir', 'https://toptalent.co/Uploads/CKImages/eski%C5%9Fehir%20teknik.jpg'),
('Fırat Üniversitesi', 'firat', 'https://toptalent.co/Uploads/CKImages/f%C4%B1rat%20%C3%BCni.png'),
('Galatasaray Üniversitesi', 'gsu', 'https://toptalent.co/Uploads/CKImages/galatasaray%20%C3%BCniversitesi.png'),
('Gazi Üniversitesi', 'gazi', 'https://toptalent.co/Uploads/CKImages/gazi%20%C3%BCni.png'),
('Gaziantep İslam Bilim ve Teknoloji Üniversitesi', 'http:', 'https://toptalent.co/Uploads/CKImages/cropped-logo-g%C4%B1sbu-1-2.png'),
('Gaziantep Üniversitesi', 'gantep', 'https://toptalent.co/Uploads/CKImages/gaziantep_universitesi.png'),
('Gebze Teknik Üniversitesi', 'gtu', 'https://toptalent.co/Uploads/CKImages/gebze%20teknik.png'),
('Giresun Üniversitesi', 'giresun', 'https://toptalent.co/Uploads/CKImages/Giresun_%C3%9Cniversitesi_Logo.png'),
('Gümüşhane Üniversitesi', 'gumushane', 'https://toptalent.co/Uploads/CKImages/g%C3%BCm%C3%BC%C5%9Fhane%20%C3%BCni.png'),
('Hacettepe Üniversitesi', 'hacettepe', 'https://toptalent.co/Uploads/CKImages/hacettepe%20%C3%BCni.png'),
('Hakkari Üniversitesi', 'hakkari', 'https://toptalent.co/Uploads/CKImages/Hakkari_%C3%9Cniversitesi_logosu.png'),
('Harran Üniversitesi', 'harran', 'https://toptalent.co/Uploads/CKImages/Harran_%C3%9Cniversitesi_logo.png'),
('Hatay Mustafa Kemal Üniversitesi', 'mku', 'https://toptalent.co/Uploads/CKImages/hatay%20mustafa%20kemal%20%C3%BCniversitesi.png'),
('Hitit Üniversitesi', 'hitit', 'https://toptalent.co/Uploads/CKImages/hitit%20%C3%BCni.png'),
('Iğdır Üniversitesi', 'igdir', 'https://toptalent.co/Uploads/CKImages/%C4%B1%C4%9Fd%C4%B1r%20%C3%BCni.jpg'),
('Isparta Uygulamalı Bilimler Üniversitesi', 'isparta', 'https://toptalent.co/Uploads/CKImages/%C4%B1sparta%20uygulamal%C4%B1%20bilimler.png'),
('İnönü Üniversitesi', 'inonu', 'https://toptalent.co/Uploads/CKImages/In%C3%B6n%C3%BC_%C3%BCniversitesi_logo.gif'),
('İskenderun Tenik Üniversitesi', 'iste', 'https://toptalent.co/Uploads/CKImages/iskenderun%20teknik.png'),
('İstanbul Medeniyet Üniversitesi', 'medeniyet', 'https://toptalent.co/Uploads/CKImages/istanbul%20medeniyet%20%C3%BCni.png'),
('İstanbul Teknik Üniversitesi', 'itu', 'https://toptalent.co/Uploads/CKImages/istanbul%20teknik.png'),
('İstanbul Üniversitesi', 'istanbul', 'https://toptalent.co/Uploads/CKImages/istanbul%20%C3%BCniversitesi.png'),
('İstanbul Üniversitesi-Cerrahpaşa', 'istanbulc', 'https://toptalent.co/Uploads/CKImages/330px-Istanbul_%C3%BCniversitesi-cerrahpa%C5%9Fa_logosu.png'),
('İzmir Bakırçay Üniversitesi', 'bakircay', 'https://toptalent.co/Uploads/CKImages/izmir%20bak%C4%B1r%C3%A7ay.png'),
('İzmir Demokrasi Üniversitesi', 'idu', 'https://toptalent.co/Uploads/CKImages/izmir%20demokrasi%20%C3%BCni.jpg'),
('İzmir Katip Çelebi Üniversitesi', 'ikc', 'https://toptalent.co/Uploads/CKImages/izmir%20katip%20%C3%A7elebi.png'),
('İzmir Yüksek Teknoloji Enstitüsü', 'iyte', 'https://toptalent.co/Uploads/CKImages/iyte_logo-tur.png'),
('Kafkas Üniversitesi', 'kafkas', 'https://toptalent.co/Uploads/CKImages/kafkas%20%C3%BCni.png'),
('Kahramanmaraş İstiklal Üniversitesi', 'istiklal', 'https://toptalent.co/Uploads/CKImages/kahramanmara%C5%9F%20istiklal.png'),
('Kahramanmaraş Sütçü İmam Üniversitesi', 'ksu', 'https://toptalent.co/Uploads/CKImages/kahramanmara%C5%9F%20s%C3%BCt%C3%A7%C3%BC%20imam.jpg'),
('Karabük Üniversitesi', 'karabuk', 'https://toptalent.co/Uploads/CKImages/karab%C3%BCk%20%C3%BCniversitesi.png'),
('Karadeniz Teknik Üniversitesi', 'ktu', 'https://toptalent.co/Uploads/CKImages/karadeniz%20teknik%20%C3%BCni.png'),
('Karamanoğlu Mehmetbey Üniversitesi', 'kmu', 'https://toptalent.co/Uploads/CKImages/karamano%C4%9Flu%20mehmetbey%20%C3%BCni.jpg'),
('Kastamonu Üniversitesi', 'kastamonu', 'https://toptalent.co/Uploads/CKImages/kastamonu%20%C3%BCni.jpg'),
('Kayseri Üniversitesi', 'kayseri', 'https://toptalent.co/Uploads/CKImages/kayseri%20%C3%BCniversitesi.png'),
('Kırıkkale Üniversitesi', 'kku', 'https://toptalent.co/Uploads/CKImages/k%C4%B1r%C4%B1kkale%20%C3%BCni.png'),
('Kırklareli Üniversitesi', 'klu', 'https://toptalent.co/Uploads/CKImages/K%C4%B1rklareli_%C3%9Cniversitesi_.jpg'),
('Kırşehir Ahi Evran Üniversitesi', 'ahievran', 'https://toptalent.co/Uploads/CKImages/k%C4%B1r%C5%9Fehir%20ahi%20evran%20%C3%BCni.png'),
('Kilis 7 Aralık Üniversitesi', 'kilis', 'https://toptalent.co/Uploads/CKImages/kilis%207%20aral%C4%B1k%20%C3%BCni.png'),
('Kocaeli Üniversitesi', 'kocaeli', 'https://toptalent.co/Uploads/CKImages/kocaeli%20%C3%BCni.jpg'),
('Konya Teknik Üniversitesi', 'ktun', 'https://toptalent.co/Uploads/CKImages/konya%20teknik.png'),
('Kütahya Dumlupınar Üniversitesi', 'dumlupinar', 'https://toptalent.co/Uploads/CKImages/k%C3%BCtahya%20dumlup%C4%B1nar%20%C3%BCni.jpg'),
('Kütahya Sağlık Bilimleri Üniversitesi', 'ksbu', 'https://toptalent.co/Uploads/CKImages/k%C3%BCtahya%20sa%C4%9Fl%C4%B1k%20bilimleri%20%C3%BCni.png'),
('Malatya Turgut Özal Üniversitesi', 'ozal', 'https://toptalent.co/Uploads/CKImages/malatya%20turgut%20%C3%B6zal.png'),
('Manisa Celal Bayar Üniversitesi', 'mcbu', 'https://toptalent.co/Uploads/CKImages/manisa%20celal%20bayar(1).png'),
('Mardin Artuklu Üniversitesi', 'artuklu', 'https://toptalent.co/Uploads/CKImages/mardin%20artuklu%20%C3%BCni.jpg'),
('Marmara Üniversitesi', 'marmara', 'https://toptalent.co/Uploads/CKImages/marmara%20%C3%BCni.png'),
('Mersin Üniversitesi', 'mersin', 'https://toptalent.co/Uploads/CKImages/mersin%20%C3%BCni.png'),
('Milli Savunma Üniversitesi (Askeri)', 'msu', 'https://toptalent.co/Uploads/CKImages/MilliSavunmaUniversitesiLogo.png'),
('Mimar Sinan Güzel Sanatlar Üniversitesi', 'msgsu', 'https://toptalent.co/Uploads/CKImages/mimar%20sinan%20g%C3%BCzel%20sanatlar.jpg'),
('Muğla Sıtkı Koçman Üniversitesi', 'mu', 'https://toptalent.co/Uploads/CKImages/Mu%C4%9Fla_S%C4%B1tk%C4%B1_Ko%C3%A7man_%C3%9Cniversitesi_logo.png'),
('Munzur Üniversitesi', 'munzur', 'https://toptalent.co/Uploads/CKImages/munzur%20%C3%BCni.png'),
('Muş Alparslan Üniversitesi', 'alparslan', 'https://toptalent.co/Uploads/CKImages/mu%C5%9F%20alparslan%20%C3%BCni.jpg'),
('Necmettin Erbakan Üniversitesi', 'erbakan', 'https://toptalent.co/Uploads/CKImages/necmettin%20erbakan%20%C3%BCni.png'),
('Nevşehir Hacı Bektaş Veli Üniversitesi', 'nevsehir', 'https://toptalent.co/Uploads/CKImages/nev%C5%9Fehir%20hac%C4%B1%20bekta%C5%9F%20veli.jpg'),
('Niğde Ömer Halisdemir Üniversitesi', 'ohu', 'https://toptalent.co/Uploads/CKImages/ni%C4%9Fde%20%C3%B6mer%20halisdemir%20%C3%BCni.jpg'),
('Ondokuz Mayıs Üniversitesi', 'omu', 'https://toptalent.co/Uploads/CKImages/ondokuz%20may%C4%B1s%20%C3%BCni.png'),
('Ordu Üniversitesi', 'odu', 'https://toptalent.co/Uploads/CKImages/ordu%20%C3%BCniversitesi.png'),
('Orta Doğu Teknik Üniversitesi', 'metu', 'https://toptalent.co/Uploads/CKImages/ortad%20do%C4%9Fu%20teknik.png'),
('Osmaniye Korkut Ata Üniversitesi', 'osmaniye', 'https://toptalent.co/Uploads/CKImages/osmaniye%20korkut%20ata.jpg'),
('Pamukkale Üniversitesi', 'pau', 'https://toptalent.co/Uploads/CKImages/pamukkale%20%C3%BCni.png'),
('Recep Tayyip Erdoğan Üniversitesi', 'erdogan', 'https://toptalent.co/Uploads/CKImages/recep%20tayyip%20erdo%C4%9Fan%20%C3%BCniversitesi.jpg'),
('Sağlık Bilimleri Üniversitesi', 'sbu', 'https://toptalent.co/Uploads/CKImages/sa%C4%9Fl%C4%B1k%20bilimleri.jpg'),
('Sakarya Uygulamalı Bilimler Üniversitesi', 'subu', 'https://toptalent.co/Uploads/CKImages/sakarya%20uygulamal%C4%B1%20bilimler.png'),
('Sakarya Üniversitesi', 'sakarya', 'https://toptalent.co/Uploads/CKImages/sakarya%20%C3%BCni.png'),
('Samsun Üniversitesi', 'samsun', 'https://toptalent.co/Uploads/CKImages/samsun%20%C3%BCni.png'),
('Selçuk Üniversitesi', 'selcuk', 'https://toptalent.co/Uploads/CKImages/sel%C3%A7uk%20%C3%BCni.png'),
('Siirt Üniversitesi', 'siirt', 'https://toptalent.co/Uploads/CKImages/yen-logo-dikey-siirt-201886105211696.png'),
('Sinop Üniversitesi', 'sinop', 'https://toptalent.co/Uploads/CKImages/sinop%20%C3%BCniversitesi.png'),
('Sivas Bilim ve Teknoloji Üniversitesi', '', 'https://toptalent.co/Uploads/CKImages/logo(2).png'),
('Sivas Cumhuriyet Üniversitesi', 'cumhuriyet', 'https://toptalent.co/Uploads/CKImages/sivas%20cumhuriyet.jpg'),
('Süleyman Demirel Üniversitesi', 'sdu', 'https://toptalent.co/Uploads/CKImages/s%C3%BCleyman%20demirel%20%C3%BCni.jpg'),
('Şırnak Üniversitesi', 'sirnak', 'https://toptalent.co/Uploads/CKImages/%C5%9F%C4%B1rnak%20%C3%BCni.jpg'),
('Tarsus Üniversitesi', 'tarsus', 'https://toptalent.co/Uploads/CKImages/tarsus%20%C3%BCni.jpg'),
('Tekirdağ Namık Kemal Üniversitesi', 'nku', 'https://toptalent.co/Uploads/CKImages/tekirda%C4%9F%20nam%C4%B1k%20kemal.jpg'),
('Tokat Gaziosmanpaşa Üniversitesi', 'gop', 'https://toptalent.co/Uploads/CKImages/tokat%20gaziosman%20pa%C5%9Fa.png'),
('Trabzon Üniversitesi', 'trabzon', 'https://toptalent.co/Uploads/CKImages/trabzon%20uni.png'),
('Trakya Üniversitesi', 'trakya', 'https://toptalent.co/Uploads/CKImages/trakya%20uni.png'),
('Türk-Alman Üniversitesi', 'tau', 'https://toptalent.co/Uploads/CKImages/t%C3%BCrk-alman%20uni.png'),
('Türk-Japon Bilim ve Teknoloji Üniversitesi', 'tju', 'https://toptalent.co/Uploads/CKImages/Tju_logo1.png'),
('Uşak Üniversitesi', 'usak', 'https://toptalent.co/Uploads/CKImages/u%C5%9Fak%20%C3%BCni.png'),
('Van Yüzüncü Yıl Üniversitesi', 'yyu', 'https://toptalent.co/Uploads/CKImages/van%20y%C3%BCz%C3%BCnc%C3%BC%20y%C4%B1l.png'),
('Yalova Üniversitesi', 'yalova', 'https://toptalent.co/Uploads/CKImages/yalova%20uni.png'),
('Yıldız Teknik Üniversitesi', 'yildiz', 'https://toptalent.co/Uploads/CKImages/y%C4%B1ld%C4%B1z%20teknik.png'),
('Yozgat Bozok Üniversitesi', 'bozok', 'https://toptalent.co/Uploads/CKImages/YOZGAT%20bozok.png'),
('Zonguldak Bülent Ecevit Üniversitesi', 'beun', 'https://toptalent.co/Uploads/CKImages/ZONGULDAK%20b%C3%BClent%20ecevit.png'),
('Üniversite Adı', '', ''),
('Acıbadem Üniversitesi', 'acibadem', 'https://toptalent.co/Uploads/CKImages/ac%C4%B1badem%20mehmet%20ali%20ayd%C4%B1nlar.png'),
('Alanya Hamdullah Emin Paşa Üniversitesi', 'alanyahep', 'https://toptalent.co/Uploads/CKImages/alanya%20hamdullah%20pa%C5%9Fa.png'),
('Altınbaş Üniversitesi', 'altinbas', 'https://toptalent.co/Uploads/CKImages/alt%C4%B1nba%C5%9F%20%C3%BCniversitesi.png'),
('Anka Teknoloji Üniversitesi', 'anka', 'https://toptalent.co/Uploads/CKImages/anka%20teknoloji%20%C3%BCni.jpg'),
('Ankara Medipol Üniversitesi', 'ankaramedipol', 'https://toptalent.co/Uploads/CKImages/450px-Ankara_Medipol_%C3%9Cniversitesi_logosu.svg(1).png'),
('Antalya AKEV Üniversitesi', 'akev', 'https://toptalent.co/Uploads/CKImages/antalya%20AKEV(1).png'),
('Antalya Bilim Üniversitesi', 'antalya', 'https://toptalent.co/Uploads/CKImages/antalya%20bilim.jpg'),
('Ataşehir Adıgüzel Meslek Yüksekokulu', 'adiguzel', 'https://toptalent.co/Uploads/CKImages/ata%C5%9Fehir%20ad%C4%B1g%C3%BCzel%20myo.png'),
('Atılım Üniversitesi', 'atilim', 'https://toptalent.co/Uploads/CKImages/at%C4%B1l%C4%B1m%20%C3%BCni.jpg'),
('Avrasya Üniversitesi', 'avrasya', 'https://toptalent.co/Uploads/CKImages/avrasya%20%C3%BCni.png'),
('Bahçeşehir Üniversitesi', 'bau', 'https://toptalent.co/Uploads/CKImages/Bah%C3%A7e%C5%9Fehir_%C3%9Cniversitesi_logo.jpg'),
('Başkent Üniversitesi', 'baskent', 'https://toptalent.co/Uploads/CKImages/ba%C5%9Fkent%20%C3%BCni.png'),
('Beykent Üniversitesi', 'beykent', 'https://toptalent.co/Uploads/CKImages/beykent%20%C3%BCni.jpg'),
('Beykoz Üniversitesi', 'beykoz', 'https://toptalent.co/Uploads/CKImages/beykoz%20%C3%BCni.png'),
('Bezmiâlem Vakıf Üniversitesi', 'bezmialem', 'https://toptalent.co/Uploads/CKImages/bezmialem%20vak%C4%B1f.png'),
('Biruni Üniversitesi', 'biruni', 'https://toptalent.co/Uploads/CKImages/biruni%20%C3%BCni.png'),
('Çağ Üniversitesi', 'cag', 'https://toptalent.co/Uploads/CKImages/%C3%A7a%C4%9F%20%C3%BCni.png'),
('Çankaya Üniversitesi', 'cankaya', 'https://toptalent.co/Uploads/CKImages/%C3%A7ankaya%20%C3%BCniversitesi.jpg'),
('Demiroğlu Bilim Üniversitesi', 'bilim', 'https://toptalent.co/Uploads/CKImages/flogo-footer.png'),
('Doğuş Üniversitesi', 'dogus', 'https://toptalent.co/Uploads/CKImages/do%C4%9Fu%C5%9F%20%C3%BCniversitesi.png'),
('Fatih Sultan Mehmet Vakıf Üniversitesi', 'fatihsultan', 'https://toptalent.co/Uploads/CKImages/fatih%20sm%20uni.png'),
('Fenerbahçe Üniversitesi', 'fbu', 'https://toptalent.co/Uploads/CKImages/fenerbah%C3%A7e%20uni.png'),
('Haliç Üniversitesi', 'halic', 'https://toptalent.co/Uploads/CKImages/hali%C3%A7%20%C3%BCni.jpg'),
('Hasan Kalyoncu Üniversitesi', 'hku', 'https://toptalent.co/Uploads/CKImages/hasan%20kalyoncu%20uni.png'),
('İbn Haldun Üniversitesi', 'ihu', 'https://toptalent.co/Uploads/CKImages/istanbul%20ibn-haldun.png'),
('Işık Üniversitesi', 'isikun', 'https://toptalent.co/Uploads/CKImages/%C4%B1%C5%9F%C4%B1k%20%C3%BCni.png'),
('İhsan Doğramacı Bilkent Üniversitesi', 'bilkent', 'https://toptalent.co/Uploads/CKImages/ihsan%20do%C4%9Framac%C4%B1%20bilkent.png'),
('İstanbul 29 Mayıs Üniversitesi', '29mayis', 'https://toptalent.co/Uploads/CKImages/istanbul%2029%20may%C4%B1s.jpg'),
('İstanbul Arel Üniversitesi', 'arel', 'https://toptalent.co/Uploads/CKImages/istanbul%20arel.png'),
('İstanbul Atlas Üniversitesi', 'atlas', 'https://toptalent.co/Uploads/CKImages/istanbul-atlas.png'),
('İstanbul Aydın Üniversitesi', 'aydin', 'https://toptalent.co/Uploads/CKImages/istanbul%20ayd%C4%B1n.jpg'),
('İstanbul Ayvansaray Üniversitesi', 'ayvansaray', 'https://toptalent.co/Uploads/CKImages/istanbul%20ayvansaray.png'),
('İstanbul Bilgi Üniversitesi', 'bilgi', 'https://toptalent.co/Uploads/CKImages/istanbul%20bilgi.png'),
('İstanbul Esenyurt Üniversitesi', 'esenyurt', 'https://toptalent.co/Uploads/CKImages/%C4%B0stanbul_esenyurt_universitesi.png'),
('İstanbul Gedik Üniversitesi', 'gedik', 'https://toptalent.co/Uploads/CKImages/istanbul%20gedik.jpg'),
('İstanbul Gelişim Üniversitesi', 'gelisim', 'https://toptalent.co/Uploads/CKImages/istanbul%20geli%C5%9Fim.png'),
('İstanbul Kent Üniversitesi', 'kent', 'https://toptalent.co/Uploads/CKImages/istanbul%20kent%202.jpg'),
('İstanbul Kültür Üniversitesi', 'iku', 'https://toptalent.co/Uploads/CKImages/istanbul%20k%C3%BClt%C3%BCr.png'),
('İstanbul Medipol Üniversitesi', 'medipol', 'https://toptalent.co/Uploads/CKImages/istanbul%20medipol.png'),
('İstanbul Okan Üniversitesi', 'okan', 'https://toptalent.co/Uploads/CKImages/istanbul%20okan.jpg'),
('İstanbul Rumeli Üniversitesi', 'rumeli', 'https://toptalent.co/Uploads/CKImages/istanbul%20rumeli.png'),
('İstanbul Sabahattin Zaim Üniversitesi', 'izu', 'https://toptalent.co/Uploads/CKImages/istanbul%20sabahattin%20zaim.png'),
('İstanbul Sağlık ve Sosyal Bilimler Meslek Yüksekokulu', 'issb', 'https://toptalent.co/Uploads/CKImages/ssb_logo_header.png'),
('İstanbul Sağlık ve Teknoloji Üniversitesi', 'istun', 'https://toptalent.co/Uploads/CKImages/istun.logo.red.png'),
('İstanbul Şişli Meslek Yüksekokulu', 'sisli', 'https://toptalent.co/Uploads/CKImages/istanbul%20%C5%9Fi%C5%9Fli%20meslek%20y%C3%BCksekokulu.jpg'),
('İstanbul Ticaret Üniversitesi', 'ticaret', 'https://toptalent.co/Uploads/CKImages/%C4%B0stanbul_Ticaret.png'),
('İstanbul Yeni Yüzyıl Üniversitesi', 'yeniyuzyil', 'https://toptalent.co/Uploads/CKImages/istanbul%20yeni%20y%C3%BCzy%C4%B1l.jpg'),
('İstinye Üniversitesi', 'istinye', 'https://toptalent.co/Uploads/CKImages/istinye%20uni.png'),
('İzmir Ekonomi Üniversitesi', 'ieu', 'https://toptalent.co/Uploads/CKImages/izmir%20ekonomi.png'),
('İzmir Tınaztepe Üniversitesi', 'tinaztepe', 'https://toptalent.co/Uploads/CKImages/izmir%20t%C4%B1naztepe.jpg'),
('Kadir Has Üniversitesi', 'khas', 'https://toptalent.co/Uploads/CKImages/kadir%20has%20%C3%BCniversitesi.jpg'),
('Kapadokya Üniversitesi', 'kapadokya', 'https://toptalent.co/Uploads/CKImages/kapadokya%20%C3%BCniversitesi.jpg'),
('Kavram Meslek Yüksekokulu', 'kavram', 'https://toptalent.co/Uploads/CKImages/kavram%20meslek.jpg'),
('Kocaeli Sağlık ve Teknoloji Üniversitesi', 'kocaelisaglik', 'https://toptalent.co/Uploads/CKImages/logo2-1.png'),
('Koç Üniversitesi', 'ku', 'https://toptalent.co/Uploads/CKImages/ko%C3%A7%20%C3%BCniversitesi.png'),
('Konya Gıda ve Tarım Üniversitesi', 'gidatarim', 'https://toptalent.co/Uploads/CKImages/konya-gida-tarim-universitesi.png'),
('KTO Karatay Üniversitesi', 'karatay', 'https://toptalent.co/Uploads/CKImages/KTO_Karatay_%C3%9Cniversitesi.png'),
('Lokman Hekim Üniversitesi', 'lokmanhekim', 'https://toptalent.co/Uploads/CKImages/lokman%20hekim%20uni.png'),
('Maltepe Üniversitesi', 'maltepe', 'https://toptalent.co/Uploads/CKImages/maltepe%20uni.png'),
('MEF Üniversitesi', 'mef', 'https://toptalent.co/Uploads/CKImages/mef%20%C3%BCniversitesi.png'),
('Mudanya Üniversitesi', 'mudanya', 'https://toptalent.co/Uploads/CKImages/Mudanya_%C3%9Cniversitesi_Logosu(1).png'),
('Nişantaşı Üniversitesi', 'nisantasi', 'https://toptalent.co/Uploads/CKImages/ni%C5%9Fanta%C5%9F%C4%B1%20%C3%BCni.png'),
('Nuh Naci Yazgan Üniversitesi', 'nny', 'https://toptalent.co/Uploads/CKImages/nuh%20naci%20yazgan.png'),
('Ostim Teknik Üniversitesi', 'ostimteknik', 'https://toptalent.co/Uploads/CKImages/ostim%20teknik.png'),
('Özyeğin Üniversitesi', 'ozyegin', 'https://toptalent.co/Uploads/CKImages/%C3%B6zye%C4%9Fin%20%C3%BCni.jpg'),
('Piri Reis Üniversitesi', 'pirireis', 'https://toptalent.co/Uploads/CKImages/piri%20reis.jpg'),
('Sabancı Üniversitesi', 'sabanciuniv', 'https://toptalent.co/Uploads/CKImages/sabanc%C4%B1%20uni.jpg'),
('Sanko Üniversitesi', 'sanko', 'https://toptalent.co/Uploads/CKImages/sanko%20uni.png'),
('TED Üniversitesi', 'tedu', 'https://toptalent.co/Uploads/CKImages/ted%20%C3%BCni.jpg'),
('TOBB Ekonomi ve Teknoloji Üniversitesi', 'etu', 'https://toptalent.co/Uploads/CKImages/tobb%20ekonomi%20ve%20teknoloji.jpg'),
('Toros Üniversitesi', 'toros', 'https://toptalent.co/Uploads/CKImages/toros%20uni.png'),
('Türk Hava Kurumu Üniversitesi', 'https:', 'https://toptalent.co/Uploads/CKImages/t%C3%BCrk%20hava%20kurumu.jpg'),
('Ufuk Üniversitesi', 'ufuk', 'https://toptalent.co/Uploads/CKImages/ufuk.png'),
('Üsküdar Üniversitesi', 'uskudar', 'https://toptalent.co/Uploads/CKImages/%C3%BCsk%C3%BCdar%20%C3%BCni.jpg'),
('Yaşar Üniversitesi', 'yasar', 'https://toptalent.co/Uploads/CKImages/ya%C5%9Far%20%C3%BCniversitesi.jpg'),
('Yeditepe Üniversitesi', 'yeditepe', 'https://toptalent.co/Uploads/CKImages/yeditepe.jpg'),
('Yüksek İhtisas Üniversitesi', 'yuksekihtisasuniversitesi', 'https://toptalent.co/Uploads/CKImages/y%C3%BCksek%20ihtisas%20%C3%BCni.png');